
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      repositories:
        type: auto
      database: mongo

mail:
  address: "test01032020qwer@wp.pl"
  password: "supertestExtra"