
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      repositories:
        type: auto
      database: mongo

mail:
  address: "test123456super@gmail.com"
  password: "supertestExtra"